---
- name: Remove Duplicate php5 Config
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/php5/fpm/conf.d/newrelic.ini
    - /etc/php5/cli/conf.d/newrelic.ini
  tags:
    - newrelic
    - php
