---
- include: php-handlers.yml

- name: service | newrelic | started
  service:
    name: newrelic-sysmond
    state: started
    enabled: yes

- name: service | newrelic | stopped
  service:
    name: newrelic-sysmond
    state: stopped

- name: service | newrelic | restarted
  service:
    name: newrelic-sysmond
    state: restarted

- name: service | newrelic | reloaded
  service:
    name: newrelic-sysmond
    state: reloaded
